"""
CDM SAS Utilities — read/write SAS datasets via pandas.
Requires: pip install pyreadstat (optional, for .sas7bdat support)
"""
from __future__ import annotations
import os
from pathlib import Path
from typing import Optional

import pandas as pd
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill


def read_sas(sas_path: str, encoding: str = "utf-8") -> pd.DataFrame:
    """
    Read a .sas7bdat file into a pandas DataFrame.

    Parameters
    ----------
    sas_path : str
        Path to .sas7bdat file.
    encoding : str
        Character encoding (default utf-8).

    Returns
    -------
    pd.DataFrame
    """
    try:
        import pyreadstat
        df, meta = pyreadstat.read_sas7bdat(sas_path, encoding=encoding)
        return df
    except ImportError:
        return pd.read_sas(sas_path, encoding=encoding)


def sas_to_excel(sas_path: str, output_path: str,
                 sheet_name: str = "DATA") -> Workbook:
    """
    Convert a SAS dataset to an Excel workbook.

    Parameters
    ----------
    sas_path : str
        Path to .sas7bdat file.
    output_path : str
        Where to save the .xlsx file.
    sheet_name : str
        Name for the data sheet.

    Returns
    -------
    Workbook
    """
    df = read_sas(sas_path)
    wb = Workbook()
    ws = wb.active
    ws.title = sheet_name

    header_fill = PatternFill(start_color="4472C4", end_color="4472C4", fill_type="solid")
    header_font = Font(bold=True, color="FFFFFF")

    for col_idx, col_name in enumerate(df.columns, 1):
        cell = ws.cell(row=1, column=col_idx, value=col_name)
        cell.font = header_font
        cell.fill = header_fill

    for row_idx, (_, row) in enumerate(df.iterrows()):
        for col_idx, val in enumerate(row, 1):
            ws.cell(row=row_idx + 2, column=col_idx,
                    value=str(val) if pd.isna(val) else val)

    wb.save(output_path)
    return wb


def excel_to_sas(xlsx_path: str, output_dir: str,
                 sheet_name: str = "DATA") -> str:
    """
    Convert an Excel file to SAS dataset format (CSV + SAS import script).

    Parameters
    ----------
    xlsx_path : str
        Path to the .xlsx file.
    output_dir : str
        Directory to save CSV and SAS import script.
    sheet_name : str
        Sheet name to read from Excel.

    Returns
    -------
    str — path to the generated SAS import script (.sas)
    """
    df = pd.read_excel(xlsx_path, sheet_name=sheet_name)
    base_name = Path(xlsx_path).stem

    os.makedirs(output_dir, exist_ok=True)
    csv_path = os.path.join(output_dir, f"{base_name}.csv")
    df.to_csv(csv_path, index=False)

    timestamp = pd.Timestamp.now().strftime("%Y-%m-%d %H:%M:%S")
    csv_path_fwd = csv_path.replace("\\", "/")
    sas_script = f"""/* SAS Import Script — generated by CDM Toolkit v3.0 */
/* Source: {xlsx_path} */
/* Date: {timestamp} */

PROC IMPORT
    DATAFILE="{csv_path_fwd}"
    OUT={base_name}
    DBMS=CSV
    REPLACE;
    GETNAMES=YES;
    GUESSINGROWS=1000;
RUN;

PROC CONTENTS DATA={base_name}; RUN;
"""
    sas_path = os.path.join(output_dir, f"import_{base_name}.sas")
    with open(sas_path, "w", encoding="utf-8") as f:
        f.write(sas_script)

    return sas_path
